{
 "title": "0810 firewall dashboard",
 "time": { "from": "2025-08-09T20:45:34.996Z", "to": "2025-08-10T08:45:34.996Z" },
 "panels": [
  {
   "title": "Mitmproxy 탐지량",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({source=\"mitmproxy\", action=\"capture\"} [${__range}]))"
    }
   ]
  },
  {
   "title": "scapy 탐지량",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({source=\"scapy\", action=\"capture\"} [${__range}]))"
    }
   ]
  },
  {
   "title": "탐지된 IP 개수",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(2, sum by(src_ip) (count_over_time({source=\"scapy\", action=\"capture\"} | json [${__range}])))"
    }
   ]
  },
  {
   "title": "현재 로그",
   "type": "logs",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 11 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{source!~\"\"}"
    }
   ]
  }
 ]
}